CREATE TABLE USERS(
  ID INT(20) NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(20) NOT NULL COMMENT '用户名',
  PASSWORD VARCHAR(20) NOT NULL COMMENT '密码',
  NICKNAME VARCHAR(20) NOT NULL COMMENT '昵称',
  REALNAME VARCHAR(10) NOT NULL COMMENT '真实姓名',
  USER_GROUP INT(20) NOT NULL,
  MPHONE VARCHAR(13) NOT NULL COMMENT '移动电话',
  TELEPHONE VARCHAR(13) NOT NULL COMMENT '电话',
  EMAIL VARCHAR(20) NOT NULL COMMENT '邮件',
  ADDRESS VARCHAR(40) NOT NULL COMMENT '地址',
  IS_SH TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'IS股东',
  SH_CODE VARCHAR(20) NOT NULL COMMENT '分销商标示码',
  STATUS TINYINT(1) NOT NULL COMMENT '状态',
  JOIN_DATE INT(10) NOT NULL DEFAULT '0' COMMENT '注册时间',
  JOIN_IP VARCHAR(15) NOT NULL DEFAULT '""' COMMENT '注册IP',
  LAST_VISIT INT(10) NOT NULL DEFAULT '0',
  LAST_IP VARCHAR(15) NOT NULL DEFAULT '""',
  EXPIRE_DATE INT(10) NOT NULL COMMENT '过期日',
  AVATAR VARCHAR(50) NOT NULL COMMENT '头像',
  CREATED DATE NOT NULL,
  CREATEDBY VARCHAR(20) NOT NULL,
  UPDATED DATE NOT NULL,
  UPDATEDBY VARCHAR(20) NOT NULL,
  PRIMARY KEY(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE USER_ACCOUNT(
  ID INT(20) NOT NULL AUTO_INCREMENT,
  USERID INT(20) NOT NULL,
  ACC_TYPE TINYINT(1) NOT NULL COMMENT '账户类型',
  ACCOUNT VARCHAR(20) NOT NULL COMMENT '账户',
  PASSWORD VARCHAR(20) NOT NULL COMMENT '密码',
  VERIFYCODE VARCHAR(10) NOT NULL COMMENT '校验码',
  APPID VARCHAR(40) NOT NULL COMMENT '应用ID',
  APPSECRET VARCHAR(40) NOT NULL COMMENT '安全码',
  MCHID VARCHAR(40) NOT NULL,
  APIKEY VARCHAR(40) NOT NULL COMMENT 'APIKEY',
  CREATED DATE NOT NULL,
  CREATEDBY VARCHAR(20) NOT NULL,
  UPDATED DATE NOT NULL,
  UPDATEDBY VARCHAR(20) NOT NULL,
  PRIMARY KEY(ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE USER_TOKEN(
   ID INT(20) NOT NULL AUTO_INCREMENT,
   USERID INT(20) NOT NULL COMMENT '用户ID',
   TOKEN INT(40) NOT NULL,
   EXPIRE_DATE DATE NOT NULL,
   PRIMARY KEY(ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE HOTELS(
  ID INT(20) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(40) NOT NULL,
  TELEPHONE VARCHAR(20) NOT NULL,
  MPHONE VARCHAR(20) NOT NULL,
  EMAIL VARCHAR(20) NOT NULL,
  LOCATION_X FLOAT NOT NULL,
  LOCATION_Y FLOAT NOT NULL,
  ZIPCODE VARCHAR(10) NOT NULL,
  LOGO VARCHAR(200) NOT NULL,
  CREATED DATE NOT NULL,
  CREATEDBY VARCHAR(20) NOT NULL,
  UPDATED DATE NOT NULL,
  UPDATEDBY VARCHAR(20) NOT NULL,
  PRIMARY KEY(ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE ROOM_TYPE(
  ID INT( 20 ) NOT NULL AUTO_INCREMENT ,
  NAME VARCHAR( 20 ) NOT NULL ,
  SEQ TINYINT( 1 ) NOT NULL DEFAULT 0,
  PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE HOTEL_ROOM(
  ID INT(20) NOT NULL AUTO_INCREMENT,
  HOTELID INT(20) NOT NULL COMMENT '客栈ID',
  ROOMTYPE INT(20) NOT NULL COMMENT '房型',
  NAME VARCHAR(20) NOT NULL COMMENT '房名',
  PRICE FLOAT NOT NULL COMMENT '价格',
  VIP_PRICE FLOAT NOT NULL COMMENT 'VIP价格',
  ROOMS INT(2) NOT NULL COMMENT '总房间',
  FREE_ROOMS INT(2) NOT NULL COMMENT '空余房间',
  CREATED DATE NOT NULL,
  CREATEDBY VARCHAR(20) NOT NULL,
  UPDATED DATE NOT NULL,
  UPDATEDBY VARCHAR(20) NOT NULL,
  PRIMARY KEY(ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE ORDERS(
  ID INT(20) NOT NULL AUTO_INCREMENT,
  ROOMID INT(20) NOT NULL COMMENT '房间ID',
  GUESTNAME VARCHAR(20) NOT NULL COMMENT '住客名',
  MPHONE VARCHAR(13) NOT NULL COMMENT '移动电话',
  CHANNEL VARCHAR(10) NOT NULL COMMENT '来源',
  NIGHTS INT(2) NOT NULL COMMENT '总天数',
  TOTAL_PRICE FLOAT NOT NULL COMMENT '总价',
  REMARK VARCHAR(40) NOT NULL COMMENT '备注',
  PAYSTATUS TINYINT(1) DEFAULT '0' COMMENT '付款状态',
  NEEDCAR TINYINT(1) DEFAULT '0' COMMENT '需要接车',
  CHECKIN DATE NOT NULL ,
  CHECKOUT DATE NOT NULL,
  STATUS TINYINT(1),
  CREATED DATE NOT NULL,
  CREATEDBY VARCHAR(20) NOT NULL,
  UPDATED DATE NOT NULL,
  UPDATEDBY VARCHAR(20) NOT NULL,
  PRIMARY KEY(ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE ORDER_ROOMS(
  ID INT(20) NOT NULL AUTO_INCREMENT,
  ORDERID INT(20) NOT NULL COMMENT '订单ID',
  USERID INT(20) NOT NULL COMMENT '用户ID',
  ROOMID INT(20) NOT NULL COMMENT '房间ID',
  PRICE FLOAT NOT NULL COMMENT '价格',
  PRIMARY KEY(ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE ORDER_PAYMENT(
  ID INT(20) NOT NULL AUTO_INCREMENT,
  ORDERID INT(20) NOT NULL COMMENT '订单ID',
  PAYTYPE VARCHAR(10) NOT NULL COMMENT '支付类型',
  PRICE FLOAT NOT NULL COMMENT '价格',
  STATUS TINYINT(1) NOT NULL COMMENT '状态',
  PRIMARY KEY(ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
